spring:
  application:
    name: project
    jwt:
      secret: secretsecretsecretsecretsecretsss
      expiration: 3600
      refreshExpiration: 36000

  multipart:
    enabled: true
    max-file-size: 2MB
    max-request-size: 2MB
    location: /tmp

  datasource:
    url: jdbc:mysql://localhost:3306/waa_student_connect
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  file:
    upload-dir: uploads