spring:
  application:
    name: project
  
  datasource:
    url: jdbc:mysql://localhost:3306/waa-demo
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
