spring:
  application:
    name: project
    jwt:
      secret: secretsecretsecretsecretsecretsss
      expiration: 3600
      refreshExpiration: 36000

  datasource:
    url: jdbc:mysql://localhost:3306/waa-demo
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  servlet:
    context-path: /api/v1